# Generated by Django 3.2.1 on 2021-08-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('user', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200, null=True)),
                ('wallet', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
