# Generated by Django 3.2.1 on 2021-08-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
