# Generated by Django 3.2.1 on 2021-08-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0002_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active_deposit',
            field=models.IntegerField(blank=True, default=0.0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='balance',
            field=models.IntegerField(blank=True, default=0.0, max_length=200, null=True),
        ),
    ]
