# Generated by Django 3.2.1 on 2021-08-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0003_auto_20210821_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='deposit',
            field=models.IntegerField(blank=True, default=0.0, max_length=200, null=True),
        ),
    ]
