# Generated by Django 3.2.1 on 2021-08-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0007_auto_20210821_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date',
        ),
        migrations.AddField(
            model_name='member',
            name='doc',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
