# Generated by Django 3.2.1 on 2021-08-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0008_auto_20210821_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='doc',
        ),
        migrations.AddField(
            model_name='member',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
