# Generated by Django 3.2.1 on 2021-08-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0009_auto_20210821_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
