# Generated by Django 3.2.1 on 2021-08-21 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0010_alter_member_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 8, 21), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='duration',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 8, 22), null=True),
        ),
    ]
