# Generated by Django 3.2.1 on 2021-08-22 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0013_alter_member_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pay_approve',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='with_approve',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 21, 17, 38, 9, 993012), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
