# Generated by Django 3.2.1 on 2021-08-22 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0014_auto_20210821_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 21, 17, 40, 17, 516825), null=True),
        ),
    ]
