# Generated by Django 3.2.1 on 2021-08-22 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0015_alter_member_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 21, 17, 41, 45, 239696), null=True),
        ),
    ]
