# Generated by Django 3.2.1 on 2021-08-22 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0018_auto_20210821_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 21, 19, 14, 16, 25125), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='l_withraw',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='t_profit',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='t_withdraw',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
    ]
