# Generated by Django 3.2.1 on 2021-08-22 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0020_auto_20210822_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.CharField(blank=models.CharField(blank=type, max_length=200, null=True), default='pending..', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 22, 3, 0, 4, 342462), null=True),
        ),
    ]
