# Generated by Django 3.2.1 on 2021-08-22 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0024_auto_20210822_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 22, 15, 59, 29, 571394), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='ref_bal',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
