# Generated by Django 3.2.1 on 2021-08-23 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0029_auto_20210822_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='active_deposit',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='balance',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 22, 17, 55, 12, 592), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='duration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 22, 17, 55, 12, 592), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='payday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 22, 17, 55, 12, 592), null=True),
        ),
    ]
