# Generated by Django 3.2.1 on 2021-08-23 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0033_auto_20210823_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='amount',
            field=models.CharField(blank=models.CharField(blank=True, max_length=200, null=True), max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 23, 2, 16, 9, 295225), null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='his_date',
            field=models.CharField(blank=models.CharField(blank=True, max_length=200, null=True), max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(blank=models.CharField(blank=True, max_length=200, null=True), default='pending..', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 23, 2, 16, 9, 294196), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='duration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 23, 2, 16, 9, 294196), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='payday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 23, 2, 16, 9, 294196), null=True),
        ),
    ]
