# Generated by Django 3.2.1 on 2021-08-23 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0034_auto_20210823_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 23, 8, 38, 57, 63483), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 23, 8, 38, 57, 62178), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='duration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 23, 8, 38, 57, 62178), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='pay_approve',
            field=models.CharField(blank=True, default=0.0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='payday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 23, 8, 38, 57, 62178), null=True),
        ),
    ]
