# Generated by Django 3.2.1 on 2021-08-23 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0035_auto_20210823_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(blank=True, max_length=200, null=True)),
                ('fb', models.CharField(blank=True, max_length=200, null=True)),
                ('wh', models.CharField(blank=True, max_length=200, null=True)),
                ('tele', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('adm_access', models.CharField(blank=True, max_length=200, null=True)),
                ('mail', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 23, 10, 9, 47, 504877), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 23, 10, 9, 47, 504877), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='duration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 23, 10, 9, 47, 504877), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='payday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 23, 10, 9, 47, 504877), null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='invited',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
