# Generated by Django 3.2.1 on 2021-08-23 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0037_auto_20210823_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 23, 14, 13, 5, 811683), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 23, 14, 13, 5, 811683), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='duration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 23, 14, 13, 5, 811683), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='payday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 23, 14, 13, 5, 811683), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
