# Generated by Django 3.2.1 on 2021-12-03 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surecoinapp', '0038_auto_20210823_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='t_deposit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 1, 27, 33, 650339), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 1, 27, 33, 645145), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='duration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 1, 27, 33, 649340), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='l_withraw',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='payday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 3, 1, 27, 33, 649340), null=True),
        ),
    ]
